# Copyright 2026 Polymerix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Facts extraction and workspace snapshot upload."""

from __future__ import annotations

import asyncio
import bisect
import concurrent.futures
import contextlib
import gzip
import hashlib
import json
import os
import threading
from pathlib import Path
from typing import Any

import httpx
from rich.console import Console

try:
    import zstandard
except ImportError:
    zstandard = None

from dont_break.application.session_store import SessionStore
from dont_break.application.sync_cache import SyncStateCache
from dont_break.config import Settings
from dont_break.credentials import load_credentials
from dont_break.domain.errors import ApiErrorMessage, ExtractError, GatewayError, ProjectLimitError
from dont_break.domain.wire import (
    DEFAULT_SYNC_BUILD_FAILED,
    SYNC_FAILURE_UNREACHABLE,
    SyncEventType,
    SyncPhase,
    SyncProgressLabel,
    SyncResultKind,
    SyncTuning,
    SyncUploadMode,
    is_transient_sync_failure,
    parse_sync_event_type,
    parse_sync_phase,
)
from dont_break.infrastructure.facts_extract import FactsExtractRunner
from dont_break.infrastructure.gateway import GatewayClient
from dont_break.infrastructure.gateway_models import SyncJsonField as SyncField

console = Console()




_SEAL_REPLAY_STATUS = (409, 500, 502, 503, 504)






_DISCOVER_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "target",
    "build",
    "out",
    "dist",
    "bin",
    "node_modules",
    ".gradle",
    ".idea",
    ".vscode",
    "vendor",
    "Pods",
    "DerivedData",
}
_DISCOVER_EXTENSIONS = {
    ".java",
    ".kt",
    ".kts",
    ".ts",
    ".tsx",
    ".mts",
    ".cts",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
}




_MAX_FILE_BYTES = 1_048_576
_MINIFIED_LINE_CHARS = 5_000
_SNIFF_BYTES = 8_192
_GENERATED_MARKERS = ("<auto-generated", "@generated")
_GZIP_RATIO_ESTIMATE = 0.35


_FACTS_TO_SOURCE_RATIO = 8
_ZSTD_RATIO_ESTIMATE = 0.10
_ZSTD_LEVEL = 6


def _part_encoding() -> str:
    """Compression for staged part bodies: zstd when the wheel is available."""
    return "zstd" if zstandard is not None else "gzip"


def _compress_part(payload: bytes, encoding: str) -> bytes:
    if encoding == "zstd":
        if zstandard is None:
            raise ExtractError("zstd encoding requested but zstandard is not installed")
        return zstandard.ZstdCompressor(level=_ZSTD_LEVEL).compress(payload)
    return gzip.compress(payload)


def _stream_line_identity(line: str) -> tuple[str, str]:
    """(relative_path, content_fingerprint) of one raw stream line, without a full
    JSON parse (lines are ~35 KB; parsing + re-serializing the whole repo's facts
    in Python would eat the pipelining win).

    Serde field order makes both lookups unambiguous: the FIRST
    `"relative_path":"` belongs to the entry descriptor (facts come after), and
    the LAST `"content_fingerprint":"` is the real field (only `content_hash`,
    hex-only, follows it). Falls back to `json.loads` when the shape surprises.
    """
    rel = _find_json_string(line, '"relative_path":"', first=True)
    fp = _find_json_string(line, '"content_fingerprint":"', first=False)
    if rel is not None and fp is not None:
        return rel, fp
    item = json.loads(line)
    entry = item.get("entry") if isinstance(item.get("entry"), dict) else {}
    return (
        str(entry.get("relative_path") or "").strip(),
        str(item.get(SyncField.CONTENT_FINGERPRINT.value) or "").strip(),
    )


def _build_part_payload(lines: list[str | None], encoding: str) -> bytes:
    """Part body from raw stream lines: a JSON array assembled textually (the
    lines are already valid compact JSON documents), then compressed. Runs off
    the event loop."""
    payload = ("[" + ",".join(line for line in lines if line is not None) + "]").encode("utf-8")
    return _compress_part(payload, encoding)


def _assert_stream_matches_manifest(missing: list[str], extras: list[str]) -> None:
    if not missing and not extras:
        return
    parts: list[str] = []
    if missing:
        preview = ", ".join(missing[:3])
        suffix = "…" if len(missing) > 3 else ""
        parts.append(f"{len(missing)} missing from stream ({preview}{suffix})")
    if extras:
        preview = ", ".join(extras[:3])
        suffix = "…" if len(extras) > 3 else ""
        parts.append(f"{len(extras)} extra in stream ({preview}{suffix})")
    raise ExtractError(
        "Streamed extraction file set does not match sync manifest: " + "; ".join(parts)
    )


def _find_json_string(line: str, key: str, *, first: bool) -> str | None:
    at = line.find(key) if first else line.rfind(key)
    if at < 0:
        return None
    start = at + len(key)
    end = line.find('"', start)
    if end < 0:
        return None
    value = line[start:end]

    return None if "\\" in value else value


def _walker_would_skip(path: Path, size: int) -> bool:
    if size > _MAX_FILE_BYTES:
        return True
    name = path.name
    if name.endswith(".min.js") or name.endswith(".bundle.js"):
        return True
    try:
        with path.open("rb") as fh:
            head = fh.read(_SNIFF_BYTES).decode("utf-8", errors="replace")
    except OSError:
        return False
    if any(marker in head for marker in _GENERATED_MARKERS):
        return True
    run = 0
    for ch in head:
        if ch == "\n":
            run = 0
        else:
            run += 1
            if run > _MINIFIED_LINE_CHARS:
                return True
    return False


def _discover_source_files(repo_root: Path) -> list[str]:
    found: list[str] = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames[:] = [name for name in dirnames if name not in _DISCOVER_EXCLUDED_DIRS]
        current = Path(dirpath)
        for name in filenames:
            path = current / name
            if path.suffix.lower() not in _DISCOVER_EXTENSIONS:
                continue
            try:
                size = path.stat().st_size
            except OSError:
                continue
            if _walker_would_skip(path, size):
                continue
            found.append(path.relative_to(repo_root).as_posix())
    found.sort()
    return found


def _bundle_files_by_path(files: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    by_path: dict[str, dict[str, Any]] = {}
    for item in files:
        entry = item.get("entry") if isinstance(item.get("entry"), dict) else {}
        rel = str(entry.get("relative_path") or "").strip()
        if not rel:
            raise ExtractError("Facts bundle entry missing relative_path")
        if rel in by_path:
            raise ExtractError(f"Facts bundle contains duplicate path: {rel}")
        by_path[rel] = item
    return by_path


def _assert_bundle_matches_manifest(
    rel_paths: list[str], files_by_path: dict[str, dict[str, Any]]
) -> None:
    manifest_paths = set(rel_paths)
    bundle_paths = set(files_by_path)
    if manifest_paths == bundle_paths:
        return
    missing = sorted(manifest_paths - bundle_paths)
    extra = sorted(bundle_paths - manifest_paths)
    parts: list[str] = []
    if missing:
        preview = ", ".join(missing[:3])
        suffix = "…" if len(missing) > 3 else ""
        parts.append(f"{len(missing)} missing from bundle ({preview}{suffix})")
    if extra:
        preview = ", ".join(extra[:3])
        suffix = "…" if len(extra) > 3 else ""
        parts.append(f"{len(extra)} extra in bundle ({preview}{suffix})")
    raise ExtractError(
        "Facts bundle file set does not match sync manifest: " + "; ".join(parts)
    )


async def _notify_part_pipeline_ingest(
    gateway: GatewayClient,
    token: str,
    session_id: str,
    part_id: str,
) -> None:
    """Best-effort pipeline ingest (202 accepted); seal re-ingests on complete if this fails.

    Must not block the upload loop: on large repos the gateway→snapshot path can
    take minutes per part (or 524 via Cloudflare). Fire-and-forget with a short
    deadline so part PUTs keep streaming.
    """
    try:
        await asyncio.wait_for(
            gateway.notify_sync_part_uploaded(token, session_id, part_id),
            timeout=5.0,
        )
    except asyncio.TimeoutError:
        console.print(
            "[yellow]Pipeline ingest notify skipped (timeout); "
            "seal will ingest on complete.[/yellow]"
        )
    except (GatewayError, httpx.HTTPError) as exc:
        console.print(
            "[yellow]Pipeline ingest notify skipped "
            f"({exc}); seal will ingest on complete.[/yellow]"
        )


def _slice_part_files(
    rel_paths: list[str],
    files_by_path: dict[str, dict[str, Any]],
    start: int,
    end: int,
) -> list[dict[str, Any]]:
    slice_paths = rel_paths[start : end + 1]
    slice_files: list[dict[str, Any]] = []
    for rel in slice_paths:
        entry = files_by_path.get(rel)
        if entry is None:
            raise ExtractError(f"Facts bundle missing manifest file: {rel}")
        slice_files.append(entry)
    return slice_files


def _should_use_delta(pending_count: int, total_files: int) -> bool:
    if pending_count <= 0:
        return False
    threshold = max(SyncTuning.DELTA_MAX_FILES, int(total_files * SyncTuning.DELTA_MAX_RATIO))
    return pending_count <= threshold


class SyncService:
    def __init__(
        self,
        store: SessionStore,
        gateway: GatewayClient | None = None,
        extract: FactsExtractRunner | None = None,
        cache_dir: Path | None = None,
    ) -> None:
        self._store = store
        self._gateway = gateway
        self._extract = extract or FactsExtractRunner()
        self._cache_dir = cache_dir

    def open_cache(self, project_id: str) -> SyncStateCache:
        return SyncStateCache(project_id, base_dir=self._cache_dir)

    def _discover(self, repo_root: Path, verbose: bool) -> list[str]:
        """File discovery for the sync manifest. The facts-extract walker is the
        single source of truth (`--list`); the Python walk only covers binaries
        that predate the flag."""
        listed = self._extract.list_files(repo_root, verbose=verbose)
        if listed is not None:
            return listed
        return _discover_source_files(repo_root)

    async def sync(
        self,
        settings: Settings,
        workspace_id: str,
        project_id: str,
        project_path: str,
        *,
        verbose: bool = False,
        changed_paths: set[str] | None = None,
    ) -> dict[str, Any]:
        return await self._sync_incremental(
            settings,
            workspace_id,
            project_id,
            project_path,
            verbose=verbose,
            changed_paths=changed_paths,
        )

    async def _sync_incremental(
        self,
        settings: Settings,
        workspace_id: str,
        project_id: str,
        project_path: str,
        *,
        verbose: bool = False,
        changed_paths: set[str] | None = None,
    ) -> dict[str, Any]:
        await self._store.mark_sync_start()
        creds = load_credentials()
        repo_root = Path(project_path).expanduser().resolve()
        legacy_slug = self._store.project_slug.strip() or project_id.strip()
        if not legacy_slug:
            raise RuntimeError("Linked project is missing its legacy sync selector.")
        gateway = self._gateway or GatewayClient(settings)
        owned = self._gateway is None





        content_hashes: dict[str, str] = {}
        source_bytes = 0
        scan_entries = await asyncio.to_thread(
            self._extract.scan, repo_root, verbose=verbose
        )
        if scan_entries is not None:
            rel_paths = [e["relative_path"] for e in scan_entries]
            content_hashes = {e["relative_path"]: e["content_hash"] for e in scan_entries}
            source_bytes = sum(int(e.get("size") or 0) for e in scan_entries)
        else:
            rel_paths = await asyncio.to_thread(self._discover, repo_root, verbose)
        if not rel_paths:
            err = ApiErrorMessage.SYNC_NO_FILES.value
            await self._store.mark_sync_result(saved=False, error=err)
            raise RuntimeError(err)

        cache = self.open_cache(project_id)
        previous_fp = (
            cache.bundle_fingerprint
            or (self._store.bundle_fingerprint or "").strip()
            or None
        )





        prepared: dict[str, dict[str, Any]] = {}
        if previous_fp and not content_hashes:
            stale = cache.stale_paths(repo_root, rel_paths, changed_paths)
            if stale and _should_use_delta(len(stale), len(rel_paths)):
                console.print(
                    f"[dim]Targeted extraction: {len(stale)} changed file(s)…[/dim]"
                )
                await self._store.set_sync_progress(
                    5, f"{SyncProgressLabel.EXTRACTING.value} ({len(stale)})"
                )
                bundle = await asyncio.to_thread(
                    self._extract.run_files, repo_root, stale, verbose=verbose
                )
                for item in list(bundle.get(SyncField.FILES.value) or []):
                    entry = item.get("entry") if isinstance(item.get("entry"), dict) else {}
                    rel = str(entry.get("relative_path") or "").strip()
                    if rel:
                        prepared[rel] = item
            elif stale:

                previous_fp = None

        manifest = []
        for i, rel in enumerate(rel_paths):
            if rel in prepared:
                fp = str(
                    prepared[rel].get(SyncField.CONTENT_FINGERPRINT.value) or ""
                ).strip()
            else:
                fp = cache.fingerprint_for(rel)
            manifest.append(
                {
                    "index": i,
                    "relative_path": rel,
                    "content_fingerprint": fp or None,
                    SyncField.CONTENT_HASH.value: content_hashes.get(rel),
                }
            )

        try:
            if content_hashes:










                session = await gateway.create_sync_session(
                    creds.token,
                    workspace_id,
                    legacy_slug,
                    project_id=project_id,
                    file_count=len(rel_paths),
                    file_manifest=manifest,
                    previous_bundle_fingerprint=None,
                    upload_mode=SyncUploadMode.STREAMING,
                )
                pending = [
                    int(i) for i in (session.get(SyncField.PENDING_INDICES.value) or [])
                ]
                if not pending or _should_use_delta(len(pending), len(rel_paths)):
                    return await self._sync_cas_carry(
                        creds.token,
                        gateway,
                        repo_root,
                        session,
                        pending,
                        rel_paths,
                        cache=cache,
                        verbose=verbose,
                    )


                return await self._sync_sfs_cold(
                    creds.token,
                    gateway,
                    repo_root,
                    session,
                    rel_paths,
                    settings=settings,
                    cache=cache,
                    verbose=verbose,
                    source_bytes=source_bytes,
                )

            if previous_fp:
                delta_session = await gateway.create_sync_session(
                    creds.token,
                    workspace_id,
                    legacy_slug,
                    project_id=project_id,
                    file_count=len(rel_paths),
                    file_manifest=manifest,
                    previous_bundle_fingerprint=previous_fp,
                    upload_mode=SyncUploadMode.DELTA,
                )
                pending = delta_session.get(SyncField.PENDING_INDICES.value) or []

                if not pending or _should_use_delta(len(pending), len(rel_paths)):
                    console.print(
                        f"[dim]Delta sync: uploading {len(pending)} changed files…[/dim]"
                    )
                    return await self._sync_delta_parallel(
                        creds.token,
                        gateway,
                        repo_root,
                        delta_session,
                        pending,
                        rel_paths,
                        manifest=manifest,
                        prepared=prepared,
                        cache=cache,
                        verbose=verbose,
                    )

            session = await gateway.create_sync_session(
                creds.token,
                workspace_id,
                legacy_slug,
                project_id=project_id,
                file_count=len(rel_paths),
                file_manifest=manifest,
                previous_bundle_fingerprint=previous_fp,
                upload_mode=SyncUploadMode.STREAMING,
            )
            return await self._sync_sfs_cold(
                creds.token,
                gateway,
                repo_root,
                session,
                rel_paths,
                settings=settings,
                cache=cache,
                verbose=verbose,
                source_bytes=source_bytes,
            )
        except (ProjectLimitError, GatewayError, ExtractError) as exc:
            await self._store.mark_sync_result(saved=False, error=str(exc))
            if isinstance(exc, ProjectLimitError):
                raise
            raise RuntimeError(str(exc)) from exc
        finally:
            if owned:
                await gateway.aclose()

    async def _complete_and_seal(
        self,
        gateway: GatewayClient,
        token: str,
        session_id: str,
        *,
        bundle_fingerprint: str,
        repo_root: Path,
        parts: list[dict[str, Any]],
    ) -> None:
        """Close the session and make sure a seal is actually enqueued."""
        try:
            await gateway.complete_sync_session(
                token,
                session_id,
                bundle_fingerprint=bundle_fingerprint,
                repo_root=str(repo_root),
                parts=parts,
            )
            return
        except GatewayError as exc:


            if exc.status_code not in _SEAL_REPLAY_STATUS:
                raise
            console.print(
                f"[yellow]Complete returned {exc.status_code}; retrying seal…[/yellow]"
            )
        await self._retry_sync_build(gateway, token, session_id)

    async def _retry_sync_build(
        self,
        gateway: GatewayClient,
        token: str,
        session_id: str,
    ) -> None:
        """Replay the seal enqueue through a transient upstream failure.

        The gateway's 500s here carry "fetch failed": its own outbound call
        did not land, which is a blip on our side and not an answer about the
        user's project. It used to propagate raw and end the sync on the first
        try. Bounded, because a retry loop that never gives up is its own way
        of lying about what is happening — and a 4xx (a project limit, a
        rejected manifest) is never retried at all.
        """
        delay = SyncTuning.SEAL_RETRY_BASE_S
        last: GatewayError | None = None
        for attempt in range(1, SyncTuning.SEAL_RETRY_MAX_ATTEMPTS + 1):
            try:
                await gateway.retry_sync_build(token, session_id)
                return
            except GatewayError as exc:
                if not is_transient_sync_failure(exc.status_code, str(exc)):
                    raise
                last = exc
                if attempt >= SyncTuning.SEAL_RETRY_MAX_ATTEMPTS:
                    break
                console.print(
                    f"[yellow]Seal retry {attempt}/{SyncTuning.SEAL_RETRY_MAX_ATTEMPTS} "
                    f"failed ({exc}); retrying in {delay:.0f}s…[/yellow]"
                )
                await self._store.set_sync_step(
                    SyncProgressLabel.RETRYING_UNREACHABLE.value
                )
                await asyncio.sleep(delay)
                delay = min(delay * 2, SyncTuning.SEAL_RETRY_MAX_S)
        raise GatewayError(
            SYNC_FAILURE_UNREACHABLE,
            status_code=last.status_code if last is not None else None,
        ) from last

    async def _listen_sse_until_ready(
        self,
        gateway: GatewayClient,
        token: str,
        session_id: str,
    ) -> None:
        try:
            async for event in gateway.open_sync_events_sse(token, session_id):
                await self._store.on_sync_event(event)
                kind = parse_sync_event_type(event.get("t"))
                if kind is SyncEventType.PHASE and parse_sync_phase(event.get("phase")) is SyncPhase.READY:
                    return
                if kind is SyncEventType.SEALED:
                    return
                if kind is SyncEventType.FAILED:
                    return
        except (httpx.HTTPError, GatewayError, RuntimeError) as exc:



            console.print(
                f"[yellow]Sync event stream dropped ({exc}); polling session status…[/yellow]"
            )
            try:
                await self._poll_until_ready(gateway, token, session_id)
            except (httpx.HTTPError, GatewayError, RuntimeError) as poll_exc:
                console.print(
                    f"[yellow]Session status poll also failed ({poll_exc}).[/yellow]"
                )

    async def _poll_until_ready(
        self,
        gateway: GatewayClient,
        token: str,
        session_id: str,
        *,
        timeout_sec: float = 30 * 60,
        interval_sec: float = 2.0,
    ) -> None:
        deadline = asyncio.get_running_loop().time() + timeout_sec
        while asyncio.get_running_loop().time() < deadline:
            status = await gateway.get_sync_session(token, session_id)
            phase = parse_sync_phase(status.get(SyncField.PHASE.value) or status.get("phase"))
            if phase is not None:
                await self._store.on_sync_event(
                    {"t": SyncEventType.PHASE.value, "phase": phase.value}
                )
            if phase is SyncPhase.READY:
                return
            if phase is SyncPhase.FAILED:
                err = (
                    status.get("failure_message")
                    or status.get("graph_error")
                    or DEFAULT_SYNC_BUILD_FAILED
                )
                await self._store.on_sync_event(
                    {"t": SyncEventType.FAILED.value, "message": err}
                )
                return
            await asyncio.sleep(interval_sec)
        await self._store.on_sync_event(
            {
                "t": SyncEventType.FAILED.value,
                "message": "Timed out waiting for snapshot build",
            }
        )

    async def _run_facts_extract_with_progress(
        self,
        repo_root: Path,
        *,
        file_total: int,
        verbose: bool = False,
    ) -> Path:
        loop = asyncio.get_running_loop()
        progress_queue: asyncio.Queue[tuple[int, int]] = asyncio.Queue()

        def on_progress(done: int, total: int) -> None:
            loop.call_soon_threadsafe(progress_queue.put_nowait, (done, total))

        extract_task = asyncio.create_task(
            asyncio.to_thread(
                self._extract.run_facts_extract_path,
                repo_root,
                verbose=verbose,
                progress=True,
                on_progress=on_progress,
            )
        )

        while not extract_task.done():
            try:
                done, total = await asyncio.wait_for(progress_queue.get(), timeout=0.25)
            except asyncio.TimeoutError:
                continue
            count = total if total > 0 else file_total
            pct = 10 + int(30 * done / max(count, 1))
            label = f"{SyncProgressLabel.EXTRACTING.value} ({done}/{count})"
            await self._store.set_sync_progress(pct, label)

        while not progress_queue.empty():
            done, total = progress_queue.get_nowait()
            count = total if total > 0 else file_total
            pct = 10 + int(30 * done / max(count, 1))
            label = f"{SyncProgressLabel.EXTRACTING.value} ({done}/{count})"
            await self._store.set_sync_progress(pct, label)

        return await extract_task

    async def _sync_sfs_cold(
        self,
        token: str,
        gateway: GatewayClient,
        repo_root: Path,
        session: dict[str, Any],
        rel_paths: list[str],
        *,
        settings: Settings,
        cache: SyncStateCache | None = None,
        verbose: bool = False,
        source_bytes: int = 0,
    ) -> dict[str, Any]:
        session_id = str(session.get(SyncField.SESSION_ID.value) or "")
        await self._store.set_sync_session(
            session_id,
            phase=SyncPhase.UPLOADING,
            total=len(rel_paths),
            upload_mode=SyncUploadMode.STREAMING,
        )
        await self._store.set_sync_progress(5, SyncProgressLabel.STARTING.value)

        sse_task = asyncio.create_task(self._listen_sse_until_ready(gateway, token, session_id))




        streamed = await self._upload_cold_streamed(
            token,
            gateway,
            repo_root,
            session_id,
            rel_paths,
            source_bytes=source_bytes,
            verbose=verbose,
        )
        if streamed is not None:
            bundle_fp, complete_parts, files = streamed
        else:
            bundle_fp, complete_parts, files = await self._upload_cold_batch(
                token,
                gateway,
                repo_root,
                session_id,
                rel_paths,
                verbose=verbose,
            )

        await self._store.set_sync_progress(80, SyncProgressLabel.UPLOAD_COMPLETE.value)
        console.print("[dim]Upload complete — sealing snapshot (this can take a while)…[/dim]")

        await self._complete_and_seal(
            gateway,
            token,
            session_id,
            bundle_fingerprint=bundle_fp,
            repo_root=repo_root,
            parts=complete_parts,
        )

        await self._store.set_sync_progress(82, SyncProgressLabel.BUILDING_GRAPH.value)
        console.print("[dim]Building graph — waiting for READY…[/dim]")

        try:
            await sse_task
        finally:
            if not sse_task.done():
                sse_task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await sse_task

        snap = self._store.snapshot()
        if snap.sync_phase == SyncPhase.FAILED.value:
            err = snap.graph_error or DEFAULT_SYNC_BUILD_FAILED
            await self._store.mark_sync_result(saved=False, error=err)
            raise RuntimeError(err)

        await self._store.set_bundle_fingerprint(bundle_fp)
        if cache is not None:
            self._harvest_bundle_fingerprints(cache, repo_root, files, rel_paths, bundle_fp)
        await self._store.mark_sync_result(saved=True)
        console.print("[green]Cold sync complete — snapshot ready.[/green]")
        return {
            "saved": True,
            "kind": SyncResultKind.SYNC_COLD.value,
            "session_id": session_id,
        }

    async def _upload_cold_streamed(
        self,
        token: str,
        gateway: GatewayClient,
        repo_root: Path,
        session_id: str,
        rel_paths: list[str],
        *,
        source_bytes: int = 0,
        verbose: bool = False,
    ) -> tuple[str, list[dict[str, Any]], list[dict[str, Any]]] | None:
        """Pipelined cold upload: consumes the `--stream` NDJSON as files finish
        parsing, fills the upload-plan part buffers, and compresses + uploads each
        part the moment it is complete — wall time approaches max(extract, upload)
        instead of their sum, and the whole bundle never sits in RAM.

        Returns ``(bundle_fingerprint, complete_parts, harvest_files)`` or ``None``
        when the installed binary predates `--stream`.
        """
        stream = await asyncio.to_thread(self._extract.stream, repo_root, verbose=verbose)
        if stream is None:
            return None

        encoding = _part_encoding()
        estimated_bundle = max(
            source_bytes * _FACTS_TO_SOURCE_RATIO, len(rel_paths) * 2_000
        )
        ratio = _ZSTD_RATIO_ESTIMATE if encoding == "zstd" else _GZIP_RATIO_ESTIMATE
        plan = await gateway.get_sync_upload_plan(
            token,
            session_id,
            estimated_gzip_bytes=int(estimated_bundle * ratio),
            encoding=encoding,
        )
        plan_parts = sorted(
            (dict(p) for p in plan.get(SyncField.PARTS.value) or []),
            key=lambda p: int(p.get(SyncField.FILE_INDEX_START.value) or 0),
        )
        if not plan_parts:
            raise GatewayError(ApiErrorMessage.UPLOAD_PLAN_EMPTY.value)

        console.print(
            f"[dim]Streaming cold sync: {len(rel_paths)} files → "
            f"{len(plan_parts)} {encoding} part(s)…[/dim]"
        )
        total = len(rel_paths)
        index_of = {rel: i for i, rel in enumerate(rel_paths)}
        part_starts: list[int] = []
        part_states: list[dict[str, Any]] = []
        for part in plan_parts:
            start = int(part.get(SyncField.FILE_INDEX_START.value) or 0)
            end = int(part.get(SyncField.FILE_INDEX_END.value) or start)
            part_starts.append(start)
            part_states.append(
                {
                    "part": part,
                    "start": start,
                    "end": end,
                    "slots": [None] * (end - start + 1),
                    "filled": 0,
                }
            )

        loop = asyncio.get_running_loop()
        entry_queue: asyncio.Queue[Any] = asyncio.Queue(maxsize=256)
        part_queue: asyncio.Queue[dict[str, Any] | None] = asyncio.Queue(
            maxsize=SyncTuning.PART_QUEUE_DEPTH
        )
        stop = threading.Event()
        complete_parts: list[dict[str, Any]] = []
        harvest_files: list[dict[str, Any]] = []
        upload_errors: list[Exception] = []
        extras: list[str] = []
        received = 0
        uploaded = 0

        def read_stream() -> None:
            """Reader thread: raw NDJSON lines → event-loop queue. The bounded
            queue is the back-pressure (extraction pauses when uploads lag);
            `stop` unblocks the thread if the sync aborts mid-stream."""

            def put(item: Any) -> bool:
                fut = asyncio.run_coroutine_threadsafe(entry_queue.put(item), loop)
                while True:
                    try:
                        fut.result(timeout=0.5)
                        return True
                    except concurrent.futures.TimeoutError:
                        if stop.is_set():
                            fut.cancel()
                            return False

            try:
                for line in stream.iter_raw_lines():
                    if stop.is_set() or not put(line):
                        stream.kill()
                        return
                put(None)
            except BaseException as exc:
                put(exc)

        async def report_progress() -> None:

            pct = 10 + int(70 * (0.5 * received / max(total, 1) + 0.5 * uploaded / len(plan_parts)))
            if received < total:
                label = f"{SyncProgressLabel.EXTRACTING.value} ({received}/{total})"
            else:
                label = f"{SyncProgressLabel.UPLOADING_PARTS.value} ({uploaded}/{len(plan_parts)})"
            await self._store.set_sync_progress(min(pct, 79), label)

        async def upload_worker(client: httpx.AsyncClient) -> None:
            """Never raises: failures land in `upload_errors` and the worker keeps
            draining, so neither the assembly loop nor the reader can deadlock on
            a full queue."""
            nonlocal uploaded
            while True:
                state = await part_queue.get()
                if state is None:
                    return
                slots = state["slots"]
                state["slots"] = None
                if upload_errors:
                    continue
                try:
                    part = state["part"]
                    part_id = str(part.get(SyncField.PART_ID.value) or "")
                    presigned_url = str(part.get(SyncField.URL.value) or "")
                    headers = dict(part.get(SyncField.HEADERS.value) or {})
                    if not presigned_url:
                        raise GatewayError(f"Missing presigned URL for {part_id}")
                    payload = await asyncio.to_thread(_build_part_payload, slots, encoding)
                    del slots
                    res = await client.put(presigned_url, content=payload, headers=headers)
                    if res.status_code >= 400:
                        raise GatewayError(
                            f"Presigned part upload failed ({res.status_code}): {res.text[:300]}"
                        )
                    complete_parts.append(
                        {
                            SyncField.PART_ID.value: part_id,
                            SyncField.BYTE_SIZE.value: len(payload),
                            SyncField.SHA256.value: hashlib.sha256(payload).hexdigest(),
                        }
                    )
                    uploaded += 1
                    await report_progress()
                except Exception as exc:
                    upload_errors.append(exc)

        reader_task = asyncio.create_task(asyncio.to_thread(read_stream))
        worker_count = min(SyncTuning.PART_UPLOAD_PARALLELISM, len(plan_parts))
        async with httpx.AsyncClient(timeout=httpx.Timeout(600.0, connect=30.0)) as client:
            workers = [asyncio.create_task(upload_worker(client)) for _ in range(worker_count)]
            try:
                while True:
                    if upload_errors:
                        raise upload_errors[0]
                    item = await entry_queue.get()
                    if item is None:
                        break
                    if isinstance(item, BaseException):
                        raise item
                    line = item
                    rel, fp = _stream_line_identity(line)
                    index = index_of.get(rel)
                    if index is None:
                        extras.append(rel)
                        continue
                    received += 1
                    if fp:
                        harvest_files.append(
                            {
                                "entry": {"relative_path": rel},
                                SyncField.CONTENT_FINGERPRINT.value: fp,
                            }
                        )
                    at = bisect.bisect_right(part_starts, index) - 1
                    state = part_states[at]
                    offset = index - state["start"]
                    if state["slots"] is not None and state["slots"][offset] is None:
                        state["slots"][offset] = line
                        state["filled"] += 1
                        if state["filled"] == len(state["slots"]):
                            await part_queue.put(state)
                    if received % 100 == 0 or received == total:
                        await report_progress()

                missing = [
                    rel_paths[s["start"] + i]
                    for s in part_states
                    if s["slots"] is not None
                    for i, slot in enumerate(s["slots"])
                    if slot is None
                ]
                _assert_stream_matches_manifest(missing, extras)

                for _ in workers:
                    await part_queue.put(None)
                await asyncio.gather(*workers)
                if upload_errors:
                    raise upload_errors[0]
            finally:
                stop.set()
                if not reader_task.done():

                    await asyncio.to_thread(stream.kill)
                for worker in workers:
                    if not worker.done():
                        worker.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await reader_task

        end_line = stream.end or {}
        bundle_fp = str(end_line.get(SyncField.BUNDLE_FINGERPRINT.value) or "").strip()
        if not bundle_fp:
            material = "|".join(
                f"{f['entry']['relative_path']}:{f[SyncField.CONTENT_FINGERPRINT.value]}"
                for f in harvest_files
            )
            bundle_fp = hashlib.sha256(material.encode("utf-8")).hexdigest()[:16]
        complete_parts.sort(key=lambda p: str(p.get(SyncField.PART_ID.value) or ""))
        return bundle_fp, complete_parts, harvest_files

    async def _upload_cold_batch(
        self,
        token: str,
        gateway: GatewayClient,
        repo_root: Path,
        session_id: str,
        rel_paths: list[str],
        *,
        verbose: bool = False,
    ) -> tuple[str, list[dict[str, Any]], list[dict[str, Any]]]:
        """Legacy cold upload for binaries without `--stream`: full extraction to a
        bundle file, then sequential gzip part uploads."""
        console.print("[dim]Extracting facts (cold sync)…[/dim]")
        await self._store.set_sync_progress(10, SyncProgressLabel.EXTRACTING.value)
        bundle_path = await self._run_facts_extract_with_progress(
            repo_root,
            file_total=len(rel_paths),
            verbose=verbose,
        )
        bundle = self._extract.load_bundle(bundle_path)
        bundle_fp = str(bundle.get(SyncField.BUNDLE_FINGERPRINT.value) or "").strip()
        if not bundle_fp:
            raw = bundle_path.read_bytes()
            bundle_fp = hashlib.sha256(raw).hexdigest()[:16]

        await self._store.set_sync_progress(40, SyncProgressLabel.FACTS_EXTRACTED.value)

        files = list(bundle.get(SyncField.FILES.value) or [])
        files_by_path = _bundle_files_by_path(files)
        _assert_bundle_matches_manifest(rel_paths, files_by_path)

        bundle_size = bundle_path.stat().st_size
        estimated_gzip = int(bundle_size * _GZIP_RATIO_ESTIMATE)

        plan = await gateway.get_sync_upload_plan(
            token,
            session_id,
            estimated_gzip_bytes=estimated_gzip,
        )
        plan_parts = list(plan.get(SyncField.PARTS.value) or [])
        if not plan_parts:
            raise GatewayError(ApiErrorMessage.UPLOAD_PLAN_EMPTY.value)

        complete_parts: list[dict[str, Any]] = []
        console.print(f"[dim]Uploading {len(plan_parts)} part(s) to staging…[/dim]")
        await self._store.set_sync_progress(50, SyncProgressLabel.UPLOADING_PARTS.value)

        async with httpx.AsyncClient(timeout=httpx.Timeout(600.0, connect=30.0)) as client:
            for part_idx, part in enumerate(plan_parts, start=1):
                part_id = str(part.get(SyncField.PART_ID.value) or "")
                start = int(part.get(SyncField.FILE_INDEX_START.value) or 0)
                end = int(part.get(SyncField.FILE_INDEX_END.value) or start)
                slice_files = _slice_part_files(rel_paths, files_by_path, start, end)
                payload = gzip.compress(json.dumps(slice_files).encode("utf-8"))
                content_sha256 = hashlib.sha256(payload).hexdigest()
                presigned_url = str(part.get(SyncField.URL.value) or "")
                headers = dict(part.get(SyncField.HEADERS.value) or {})
                if not presigned_url:
                    raise GatewayError(f"Missing presigned URL for {part_id}")

                res = await client.put(presigned_url, content=payload, headers=headers)
                if res.status_code >= 400:
                    raise GatewayError(
                        f"Presigned part upload failed ({res.status_code}): {res.text[:300]}"
                    )




                complete_parts.append(
                    {
                        SyncField.PART_ID.value: part_id,
                        SyncField.BYTE_SIZE.value: len(payload),
                        SyncField.SHA256.value: content_sha256,
                    }
                )

                pct = 50 + int(30 * part_idx / len(plan_parts) + 0.5)
                await self._store.set_sync_progress(
                    pct,
                    f"{SyncProgressLabel.UPLOADING_PARTS.value} ({part_idx}/{len(plan_parts)})",
                )
                if part_idx == len(plan_parts) or part_idx % 4 == 0:
                    console.print(
                        f"[dim]Uploaded staging part {part_idx}/{len(plan_parts)}…[/dim]"
                    )

        return bundle_fp, complete_parts, files

    async def _sync_cas_carry(
        self,
        token: str,
        gateway: GatewayClient,
        repo_root: Path,
        session: dict[str, Any],
        pending_indices: list[int],
        rel_paths: list[str],
        *,
        cache: SyncStateCache | None = None,
        verbose: bool = False,
    ) -> dict[str, Any]:
        """Scan-first sync: the server already carried every unchanged file over by
        content hash. Extract + batch-upload ONLY the pending subset (often empty),
        then complete with zero parts — the server verifies carried/ingested slots
        and computes the bundle fingerprint itself. An unchanged repo never leaves
        UPLOADING→READY (no seal, no graph rebuild)."""
        session_id = str(session.get(SyncField.SESSION_ID.value) or "")
        await self._store.set_sync_session(
            session_id,
            phase=SyncPhase.UPLOADING,
            total=len(rel_paths),
            upload_mode=SyncUploadMode.STREAMING,
        )
        await self._store.set_sync_progress(5, SyncProgressLabel.STARTING.value)

        sse_task = asyncio.create_task(
            self._listen_sse_until_ready(gateway, token, session_id)
        )

        extracted: dict[int, dict[str, Any]] = {}
        if pending_indices:
            console.print(
                f"[dim]CAS sync: extracting {len(pending_indices)} changed file(s)…[/dim]"
            )
            await self._store.set_sync_progress(
                10, f"{SyncProgressLabel.EXTRACTING.value} ({len(pending_indices)})"
            )
            pending_paths = [rel_paths[i] for i in pending_indices]
            bundle = await asyncio.to_thread(
                self._extract.run_files, repo_root, pending_paths, verbose=verbose
            )
            by_path = _bundle_files_by_path(list(bundle.get(SyncField.FILES.value) or []))
            for index in pending_indices:
                entry = by_path.get(rel_paths[index])
                if entry is None:
                    raise ExtractError(
                        f"Targeted extraction missing pending file: {rel_paths[index]}"
                    )
                extracted[index] = entry
            await self._store.set_sync_progress(40, SyncProgressLabel.FACTS_EXTRACTED.value)

            ordered = sorted(extracted)
            chunk_size = SyncTuning.FILES_BATCH_CHUNK
            total_chunks = (len(ordered) + chunk_size - 1) // chunk_size
            for chunk_no, start in enumerate(range(0, len(ordered), chunk_size), start=1):
                chunk_indices = ordered[start : start + chunk_size]
                files = [{"file_index": i, **extracted[i]} for i in chunk_indices]
                first, last = chunk_indices[0], chunk_indices[-1]
                await gateway.put_sync_files_batch(
                    token,
                    session_id,
                    files,
                    idempotency_key=f"{session_id}:batch:{first}-{last}",
                )
                pct = 40 + int(40 * chunk_no / total_chunks + 0.5)
                await self._store.set_sync_progress(
                    pct,
                    f"{SyncProgressLabel.UPLOADING_PARTS.value} ({chunk_no}/{total_chunks})",
                )
        else:
            console.print("[dim]CAS sync: repository unchanged — nothing to upload.[/dim]")

        await self._store.set_sync_progress(80, SyncProgressLabel.UPLOAD_COMPLETE.value)

        await self._complete_and_seal(
            gateway,
            token,
            session_id,
            bundle_fingerprint="",
            repo_root=repo_root,
            parts=[],
        )

        await self._store.set_sync_progress(82, SyncProgressLabel.BUILDING_GRAPH.value)

        try:
            await sse_task
        finally:
            if not sse_task.done():
                sse_task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await sse_task

        snap = self._store.snapshot()
        if snap.sync_phase == SyncPhase.FAILED.value:
            err = snap.graph_error or DEFAULT_SYNC_BUILD_FAILED
            await self._store.mark_sync_result(saved=False, error=err)
            raise RuntimeError(err)

        if cache is not None:
            for index, entry in extracted.items():
                fp = str(entry.get(SyncField.CONTENT_FINGERPRINT.value) or "")
                if fp:
                    cache.record_file(rel_paths[index], fp, repo_root=repo_root)
            cache.prune(rel_paths)
            if extracted:



                cache.bundle_fingerprint = ""
            try:
                cache.save()
            except OSError as exc:
                console.print(
                    f"[yellow]Sync cache write failed ({exc}); next sync stays CAS.[/yellow]"
                )
        await self._store.mark_sync_result(saved=True)
        console.print("[green]CAS sync complete — snapshot ready.[/green]")
        return {
            "saved": True,
            "kind": SyncResultKind.SYNC_CAS.value,
            "session_id": session_id,
        }

    @staticmethod
    def _harvest_bundle_fingerprints(
        cache: SyncStateCache,
        repo_root: Path,
        files: list[dict[str, Any]],
        rel_paths: list[str],
        bundle_fp: str,
    ) -> None:
        """Persists the Rust-emitted per-file fingerprints so the next sync can go delta."""
        for item in files:
            entry = item.get("entry") if isinstance(item.get("entry"), dict) else {}
            rel = str(entry.get("relative_path") or "").strip()
            fp = str(item.get(SyncField.CONTENT_FINGERPRINT.value) or "").strip()
            if rel and fp:
                cache.record_file(rel, fp, repo_root=repo_root)
        cache.prune(rel_paths)
        cache.bundle_fingerprint = bundle_fp
        try:
            cache.save()
        except OSError as exc:
            console.print(f"[yellow]Sync cache write failed ({exc}); next sync may be cold.[/yellow]")

    async def _sync_delta_parallel(
        self,
        token: str,
        gateway: GatewayClient,
        repo_root: Path,
        session: dict[str, Any],
        pending_indices: list[int],
        rel_paths: list[str],
        *,
        manifest: list[dict[str, Any]] | None = None,
        prepared: dict[str, dict[str, Any]] | None = None,
        cache: SyncStateCache | None = None,
        verbose: bool = False,
    ) -> dict[str, Any]:
        session_id = str(session.get(SyncField.SESSION_ID.value) or "")
        await self._store.set_sync_session(
            session_id,
            phase=SyncPhase.UPLOADING,
            total=len(rel_paths),
            upload_mode=SyncUploadMode.DELTA,
        )



        await self._store.set_sync_progress(5, SyncProgressLabel.STARTING.value)

        sse_task = asyncio.create_task(self._listen_sse_until_ready(gateway, token, session_id))

        sem = asyncio.Semaphore(SyncTuning.UPLOAD_PARALLELISM)
        prepared_entries = prepared or {}

        fingerprints: dict[int, str] = {}
        for item in manifest or []:
            idx = int(item.get("index", -1))
            fp = str(item.get("content_fingerprint") or "")
            if idx >= 0 and fp:
                fingerprints[idx] = fp

        async def extract_one(index: int) -> tuple[int, dict[str, Any]]:
            rel = rel_paths[index]
            async with sem:
                entry = prepared_entries.get(rel)
                if entry is None:


                    entry = await asyncio.to_thread(
                        self._extract.run_single_file, repo_root, rel, verbose=verbose
                    )
                return index, entry

        if pending_indices:
            await self._store.set_sync_progress(
                10, f"{SyncProgressLabel.EXTRACTING.value} ({len(pending_indices)})"
            )
        extracted = dict(await asyncio.gather(*[extract_one(i) for i in pending_indices]))
        for index, entry in extracted.items():
            fingerprints[index] = str(entry.get(SyncField.CONTENT_FINGERPRINT.value) or "")
        if extracted:
            await self._store.set_sync_progress(40, SyncProgressLabel.FACTS_EXTRACTED.value)

        async def upload_one(index: int) -> None:
            entry = extracted[index]
            fp = fingerprints.get(index, "")
            async with sem:
                await gateway.put_sync_file(
                    token,
                    session_id,
                    index,
                    entry,
                    idempotency_key=f"{session_id}:{index}:{fp}",
                )

        async def upload_batched() -> None:
            """One PUT per chunk of files: a single manifest write server-side
            instead of a read-modify-write of the whole manifest per file."""
            ordered = sorted(extracted)
            chunk_size = SyncTuning.FILES_BATCH_CHUNK
            total_chunks = (len(ordered) + chunk_size - 1) // chunk_size
            for chunk_no, start in enumerate(range(0, len(ordered), chunk_size), start=1):
                chunk_indices = ordered[start : start + chunk_size]
                files = [
                    {"file_index": i, **extracted[i]}
                    for i in chunk_indices
                ]
                first, last = chunk_indices[0], chunk_indices[-1]
                await gateway.put_sync_files_batch(
                    token,
                    session_id,
                    files,
                    idempotency_key=f"{session_id}:batch:{first}-{last}",
                )
                pct = 40 + int(40 * chunk_no / total_chunks + 0.5)
                await self._store.set_sync_progress(
                    pct,
                    f"{SyncProgressLabel.UPLOADING_FILES.value} ({chunk_no}/{total_chunks})",
                )

        if extracted:
            try:
                await upload_batched()
            except GatewayError as exc:
                if exc.status_code in (404, 405):

                    await asyncio.gather(*[upload_one(i) for i in pending_indices])
                else:
                    raise
            await self._store.set_sync_progress(80, SyncProgressLabel.UPLOAD_COMPLETE.value)

        if cache is not None:
            for index, entry in extracted.items():
                fp = fingerprints.get(index, "")
                if fp:
                    cache.record_file(rel_paths[index], fp, repo_root=repo_root)



        bundle_material = "|".join(f"{i}:{fingerprints[i]}" for i in sorted(fingerprints))
        bundle_fp = hashlib.sha256(bundle_material.encode("utf-8")).hexdigest()[:16]
        await gateway.seal_sync_session(
            token,
            session_id,
            bundle_fingerprint=str(bundle_fp),
        )


        await self._store.set_sync_progress(82, SyncProgressLabel.BUILDING_GRAPH.value)
        console.print("[dim]Delta upload complete — waiting for the seal…[/dim]")

        try:
            await sse_task
        finally:
            if not sse_task.done():
                sse_task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await sse_task

        snap = self._store.snapshot()
        if snap.sync_phase == SyncPhase.FAILED.value:
            err = snap.graph_error or DEFAULT_SYNC_BUILD_FAILED
            await self._store.mark_sync_result(saved=False, error=err)
            raise RuntimeError(err)

        await self._store.set_bundle_fingerprint(bundle_fp)
        if cache is not None:


            for rel, entry in prepared_entries.items():
                fp = str(entry.get(SyncField.CONTENT_FINGERPRINT.value) or "")
                if fp:
                    cache.record_file(rel, fp, repo_root=repo_root)
            cache.prune(rel_paths)
            cache.bundle_fingerprint = bundle_fp
            try:
                cache.save()
            except OSError as exc:
                console.print(
                    f"[yellow]Sync cache write failed ({exc}); next sync may be cold.[/yellow]"
                )
        await self._store.mark_sync_result(saved=True)
        console.print("[green]Delta sync sealed on backend.[/green]")
        return {
            "saved": True,
            "kind": SyncResultKind.SYNC_DELTA.value,
            "session_id": session_id,
        }
